version: "3.7"
services:
  flask:
    image: distortedlogic/flask:latest
    build: .
    container_name: flask
    restart: on-failure
    command: sh /start.flask.sh
    volumes:
      - .:/app
    ports:
      - 8000:8000
