version: "3.7"
services:
  notebook:
    image: distortedlogic/jupyter:latest
    build:
      context: .
      dockerfile: Dockerfile.jupyter
    container_name: notebook
    restart: on-failure
    command: jupyter lab
    ipc: host
    volumes:
      - .:/notebooks
    environment:
      - JUPYTER_TOKEN=password
    ports:
      - 8889:8888
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
