version: "3.7"
services:
  flask:
    image: distortedlogic/flask:latest
    build: .
    container_name: flask
    restart: on-failure
    command: doppler run -- sh /start.flask.sh
    environment:
      DOPPLER_TOKEN: ${DOPPLER_TOKEN_PYTHON}
    volumes:
      - .:/app
    ports:
      - 8000:8000
